name: maslowbarrier
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.11
  - pip
  - numpy
  - pandas
  - scipy
  - statsmodels
  - matplotlib
  - openpyxl
  - pip:
    - scikit-learn
    - joblib
    - threadpoolctl